services:
  scraper:
    build: .
    volumes:
      - ./app/scraping:/app/scraping       
      - ./app/data:/app/data               
      - ./app/templates:/app/templates    
      - ./app/static:/app/static           
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
    command: python app/scraping/scraper.py
